# Generated by Django 4.2.7 on 2024-02-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
