# Generated by Django 4.2.7 on 2024-03-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Basic', max_length=100),
        ),
    ]
