# Generated by Django 4.2.7 on 2024-03-04 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0011_rename_user_shifts_employeeid_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
