# Generated by Django 4.2.7 on 2024-03-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0012_alter_shifts_employeeid_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifts',
            old_name='employeeId',
            new_name='username',
        ),
    ]
