# Generated by Django 4.2.7 on 2024-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0013_rename_employeeid_shifts_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='date',
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shiftEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shiftStart',
            field=models.DateTimeField(),
        ),
    ]
