# Generated by Django 4.2.7 on 2024-03-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0014_remove_shifts_date_alter_shifts_shiftend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='ShiftPool',
            field=models.BooleanField(default=False),
        ),
    ]
