# Generated by Django 4.2.7 on 2024-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0015_shifts_shiftpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='shiftHourEnd',
            field=models.TimeField(default='5:00'),
        ),
        migrations.AddField(
            model_name='shifts',
            name='shiftHourStart',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shiftEnd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shiftStart',
            field=models.DateField(),
        ),
    ]
