# Generated by Django 4.2.7 on 2024-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0017_remove_shifts_shifthourend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='shiftEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shiftStart',
            field=models.DateTimeField(),
        ),
    ]
