# Generated by Django 4.2.7 on 2024-03-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0018_alter_shifts_shiftend_alter_shifts_shiftstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
