# Generated by Django 4.2.7 on 2024-03-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0019_shifts_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='dateAvailable',
            field=models.DateField(default=None),
        ),
    ]
