# Generated by Django 4.2.7 on 2024-03-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0020_shifts_dateavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='dateAvailable',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
