# Generated by Django 4.2.7 on 2024-03-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0021_alter_shifts_dateavailable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='qualifications',
        ),
        migrations.AddField(
            model_name='shifts',
            name='location',
            field=models.CharField(default='YVR', max_length=100),
        ),
        migrations.AddField(
            model_name='shifts',
            name='moneyAmount',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='shifts',
            name='qualification',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
