# Generated by Django 4.2.7 on 2024-03-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0022_rename_role_user_qualifications_shifts_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='Matching',
            field=models.BooleanField(default=False),
        ),
    ]
