# Generated by Django 4.2.7 on 2024-03-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0023_shifts_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='locationNotWillingToWork',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
