# Generated by Django 4.2.7 on 2024-04-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0025_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
