# Generated by Django 4.2.7 on 2024-04-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftApp', '0026_user_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_module_perms',
        ),
    ]
